#!/usr/bin/env python3
"""
Constantes Mina - Liste exhaustive des produits valides.
Utilisé pour contraindre le LLM à ne citer que des vrais produits.
"""

PRODUITS_VALIDES = [
    "Bandeau Skinminute",
    "Base Durcissante",
    "Base Fortifiante",
    "Base Réparatrice",
    "Base Égalisante",
    "Baume Riche Réparateur ++",
    "Baume à lèvres Kiss Minute",
    "Brosse nettoyante",
    "Cartouche de cire Roll-On",
    "Cire Traditionnelle Karité 1kg",
    "Collagène en Brumisateur Premium",
    "Contour des Yeux Regard Liftant Metabolissime",
    "Crème Collagène PRO Metabolic",
    "Crème Douche Hydra-Douceur",
    "Crème Douche Nourrissante",
    "Crème Equilibre Express S-détox",
    "Crème Jour Premium à la Rose Alpine Eternelle Suisse",
    "Crème Mains Edelweiss",
    "Crème MattExpert 24h S-Détox",
    "Crème Nuit Premium à la Rose Alpine Eternelle Suisse",
    "Crème Repulpante Metabolic",
    "Crème Ultra Apaisante Sensimine",
    "Crème Ultra Nourrissante Sensimine",
    "Crème Waterbomb Hydratempo",
    "Crème hydratante bébé",
    "Dissolvant Doux",
    "Dissolvant pour vernis semi-permanent",
    "Démaq' Express 3 en 1",
    "Eau micellaire à l'Aloe Vera",
    "Elixir Cell Flash Metabolissime",
    "Gel Contour des Yeux Metabolic",
    "Gel Crème Cryo",
    "Gel Douche Rafraichissant",
    "Gel Douche Relaxant",
    "Gel Mousse Floral",
    "Gel Mousse S-détox",
    "Gel Perfect Illuminateur de Teint Metabolic",
    "Gel Snap Spot S-détox",
    "Gel lavant doux bébé",
    "Glow Kit Skinminute",
    "Gommage Visage Peeling Professionnel",
    "Gomme Exfoliant",
    "Huile Nourissante",
    "Huile Satin Sublissime",
    "Huile de massage bébé",
    "HyA 3D Sérum Hydratempo",
    "HyA Crème 24h Hydratempo",
    "Kit Détox Skinminute",
    "Kit de Dépose Vernis Semi-Permanent",
    "Lait Corps Apaisant Absorption ++",
    "Lait corps doux bébé",
    "Lait démaq' visage et yeux",
    "Masque PRO 1.0 S-détox",
    "Masque PRO 2.0 Sensimine",
    "Masque PRO 4.0 Hydratempo",
    "Masque PRO 8.0 Metabolissime",
    "Masque Waterbomb",
    "Roll-on Quartz Améthyste",
    "Roll-on Quartz Cristal",
    "Roll-on Quartz Rose",
    "Savon Exfoliant Doux à l'Avoine",
    "Savon Exfoliant Intense aux Pépins de Raisin",
    "Savon Exfoliant Modéré aux Algues Rouges",
    "Shampoo Antipelliculaire",
    "Shampoo Cheveux Abîmés",
    "Shampoo Cheveux Colorés",
    "Shampoo Deluxe 3D Volume",
    "Soin Cell Flash Activateur Global Metabolissime",
    "Soin Fortifiant Après-Shampooing",
    "Soin Profond Hyper Hydratant",
    "Sos poil sous peau",
    "Stylo Magique",
    "Sérum PRO 1.0 S-détox",
    "Sérum PRO 1.3 Anti-comédons S-détox",
    "Sérum PRO 2.0 Sensimine",
    "Sérum PRO 4.0 Hydratempo",
    "Sérum Perfect Immuno-Cell Metabolic",
    "Sérum Premium 3D Volumizer",
    "Sérum Sculptant Anti-cellulite",
    "Sérum Spray Anti-acné S-détox",
    "Sérum Vitamine C PRO",
    "Toniq' 3 Fleurs Soft",
    "Toniq' S-détox",
    "Top Coat Glossy",
    "Top Coat Matt",
    "Trousse beauté",
    "Vernis Acerola - Les Rouges",
    "Vernis Amor Amor - Les Rouges",
    "Vernis Antique Pink - Les Roses",
    "Vernis Black Cherry - Les Rouges",
    "Vernis Blue Cotton - Les Pastels",
    "Vernis Bordeaux - Les Rouges",
    "Vernis Caffè Latte - Les Nudes",
    "Vernis Chocolat - Les Nudes",
    "Vernis Coquelicot - Les Rouges",
    "Vernis Corail - Les Rouges",
    "Vernis Dulce De Leche - Les Nudes",
    "Vernis Flirt - Les Roses",
    "Vernis Fuschia - Les Roses",
    "Vernis Guimauve - Les Pastels",
    "Vernis Hibiscus - Les Roses",
    "Vernis Mocha - Les Nudes",
    "Vernis Peach - Les Pastels",
    "Vernis Perfect White - Les Intemporels",
    "Vernis Pink Flower - Les Roses",
    "Vernis Plum - Les Roses",
    "Vernis Praline - Les Nudes",
    "Vernis Pure Black - Les Intemporels",
    "Vernis Raspberry - Les Roses",
    "Vernis Red Scarlet - Les Rouges",
    "Vernis Rose French - Les Roses",
    "Vernis Rubis - Les Rouges",
    "Vernis Sunny Light - Les Pastels",
    "Vernis Sweet Candy - Les Pastels",
    "Vernis Terracotta - Les Nudes",
    "Vernis Vanilla - Les Nudes",
    "Élixir de Massage",
]

# Version formatée pour injection dans les prompts LLM
PRODUITS_PROMPT = ", ".join(PRODUITS_VALIDES[:30]) + " ... (et 87 autres produits)"

def get_produits_for_prompt(max_items: int = 20) -> str:
    """Retourne une liste formatée pour les prompts LLM."""
    sample = PRODUITS_VALIDES[:max_items]
    return "\n".join(f"- {p}" for p in sample) + f"\n... et {len(PRODUITS_VALIDES) - max_items} autres produits"
